# Generated by Django 4.1.2 on 2022-12-02 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_wheat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wheat',
            name='date',
        ),
    ]
