# Generated by Django 4.1.2 on 2022-12-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_wheat_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheat',
            name='weight',
            field=models.FloatField(),
        ),
    ]
