# Generated by Django 4.1.2 on 2022-12-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_wheat_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
